class ErrorCodes:
    """
    Códigos de error utilizados por toda la API.

    Facilitan la identificación de errores desde
    aplicaciones frontend y clientes externos.
    """

    VALIDATION_ERROR = "VALIDATION_ERROR"

    NOT_FOUND = "NOT_FOUND"

    PERMISSION_DENIED = "PERMISSION_DENIED"

    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"

    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    DOCUMENT_ALREADY_EXISTS = "DOCUMENT_ALREADY_EXISTS"

    ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS"

    USER_INACTIVE = "USER_INACTIVE"

    ROLE_INACTIVE = "ROLE_INACTIVE"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    USER_ROLE_ALREADY_EXISTS = "USER_ROLE_ALREADY_EXISTS"

    NO_ACTIVE_ROLE = "NO_ACTIVE_ROLE"

    NO_PERMISSIONS = "NO_PERMISSIONS"
